name: CustomTrades
version: '${version}'
main: de.customtrades.CustomTradesPlugin
api-version: '1.21'
description: Custom Trader NPCs with advanced trading features
author: YourName

# Paper-specific configuration
bootstrapper: de.customtrades.CustomTradesBootstrapper
loader: de.customtrades.CustomTradesLoader

commands:
  customtrades:
    description: Main CustomTrades command
    aliases: [ct, trade, trades]
    permission: customtrades.use
    usage: |
      /<command> create <name> <mob> - Create a trader
      /<command> edit - Edit a trader
      /<command> remove <name> - Remove a trader
      /<command> list - List all traders
      /<command> reload - Reload all traders

permissions:
  customtrades.use:
    description: Access to all commands
    default: op
  customtrades.create:
    description: Create traders
    default: op
  customtrades.edit:
    description: Edit traders
    default: op
  customtrades.remove:
    description: Remove traders
    default: op
  customtrades.list:
    description: List all traders
    default: op
  customtrades.reload:
    description: Reload traders
    default: op

dependencies:
  server:
    PlayerPoints:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: true

